# Generated by Django 4.0.4 on 2023-05-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'stream',
                'verbose_name_plural': 'stream',
                'db_table': 'stream',
            },
        ),
    ]
