# Generated by Django 4.0.4 on 2023-05-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'verbose_name': 'stream', 'verbose_name_plural': 'streams'},
        ),
    ]
